### ISSUE TITLE
A new issue

### ISSUE THREAD

**Issue by andresmgsl** [andresmgsl/translegal#3]

**Comment by ghost** [comment]
# ⚠️ Bounty Failed

```sh
Cannot read properties of null (reading 'id')
```

**Comment by ghost** [comment]
# 🔐 Bounty Closed
This issue's bounty is currently closed. [Inspect the transaction](https://explorer.solana.com/tx/2EmXG4qUc6pEYViMB8CyTKwUCsmfHGSwWySqexz1zSUTUzif1E1kAWgfrbRNQLuj9BEb6ix8phghBYT9HJzca7um?cluster=custom&customUrl=https%3A%2F%2Fapi.devnet.solana.com) in the Solana Explorer.
